export type Lang = 'ar' | 'fr' | 'en';
export const LANG_KEY = 'pointage_lang';

export function getSavedLang(): Lang {
  if (typeof window === 'undefined') return 'ar';
  return (localStorage.getItem(LANG_KEY) as Lang) || 'ar';
}
export function saveLang(lang: Lang) {
  localStorage.setItem(LANG_KEY, lang);
}
export function isRTL(lang: Lang) {
  return lang === 'ar';
}

const T = {
  ar: {
    // Navbar
    nav_dashboard: 'لوحة القيادة', nav_workers: 'العمال', nav_attendance: 'تسجيل الحضور',
    nav_reports: 'التقارير', nav_archive: 'الأرشيف', nav_changePass: 'تغيير كلمة المرور', nav_logout: 'تسجيل الخروج',
    // Common
    cancel: 'إلغاء', save: 'حفظ', edit: 'تعديل', archive_btn: 'أرشفة',
    restore: '♻️ استرجاع', delete_final: 'حذف نهائي', confirm: 'تأكيد',
    present: 'حاضر', absent: 'غائب', late: 'متأخر', leave: 'إجازة',
    // Password modal
    change_pass_title: 'تغيير كلمة المرور', current_pass: 'كلمة المرور الحالية',
    new_pass: 'كلمة المرور الجديدة', confirm_pass: 'تأكيد كلمة المرور',
    pass_changed: 'تم تغيير كلمة المرور بنجاح',
    // Dashboard
    dash_title: 'لوحة القيادة', total_workers: 'إجمالي العمال', present_today: 'حاضرون اليوم',
    absent_today: 'غائبون اليوم', late_today: 'متأخرون', on_leave: 'في إجازة',
    not_recorded: 'لم يُسجَّل بعد', absent_list: 'الغائبون اليوم', no_absents: 'لا يوجد غائبون مسجلون',
    quick_links: 'روابط سريعة', link_attendance: 'تسجيل حضور اليوم', link_workers: 'إدارة العمال',
    link_reports: 'عرض التقارير', no_workers_msg: 'لا يوجد عمال مسجلون بعد', add_workers_btn: 'إضافة العمال',
    // Workers page
    workers_title: 'إدارة العمال', worker_count: 'عامل', add_worker: '+ إضافة عامل',
    edit_worker_title: 'تعديل بيانات العامل', add_worker_title: 'إضافة عامل جديد',
    full_name: 'الاسم الكامل *', name_ph: 'أدخل الاسم الكامل',
    position_lbl: 'المنصب / الوظيفة *', position_ph: 'مثال: عامل بناء، كهربائي...',
    dept_lbl: 'القسم', dept_ph: 'مثال: الإنتاج، الصيانة...', phone_lbl: 'رقم الهاتف',
    start_date: 'تاريخ الالتحاق', save_changes: 'حفظ التعديلات', add_worker_btn: 'إضافة العامل',
    change_photo: 'تغيير الصورة', add_photo: '+ إضافة صورة', delete_photo: 'حذف الصورة',
    archive_title: 'أرشفة العامل',
    archive_msg: 'سيتم نقل العامل إلى الأرشيف مع الاحتفاظ بجميع سجلات حضوره. لن يظهر في قائمة الحضور اليومي.',
    search_ph: 'بحث بالاسم أو المنصب أو القسم...', col_photo: 'الصورة', col_name: 'الاسم',
    col_position: 'المنصب', col_dept: 'القسم', col_phone: 'الهاتف', col_start: 'تاريخ الالتحاق',
    col_actions: 'إجراءات', no_workers: 'لا يوجد عمال مسجلون. أضف أول عامل.', no_results: 'لا توجد نتائج للبحث.',
    // Pointage
    pointage_title: 'تسجيل الحضور', pointage_sub: 'سجّل حضور وغياب العمال لكل يوم',
    date_lbl: 'التاريخ:', mark_all: 'تحديد الكل كـ:', col_status: 'الحالة',
    col_checkin: 'وقت الدخول', col_checkout: 'وقت الخروج', col_note: 'ملاحظة',
    add_note: '+ ملاحظة', note_title: 'إضافة ملاحظة', note_ph: 'اكتب ملاحظة هنا...',
    no_workers_pointage: 'لا يوجد عمال مسجلون', go_add_workers: 'اذهب لإضافة العمال أولاً',
    // Reports
    reports_title: 'التقارير الشهرية', reports_sub: 'ملخص الحضور والغياب لكل عامل',
    year_lbl: 'السنة:', month_lbl: 'الشهر:', worker_lbl: 'العامل:', all_workers: 'الجميع',
    download_pdf: '📄 تحميل PDF', export_excel: '📊 تصدير Excel', print_all: '📄 طباعة كل التقارير',
    export_all_excel: '📊 تصدير Excel للكل', attendance_rate: 'نسبة الحضور', col_report: 'تقرير',
    month_summary: 'ملخص الشهر', no_workers_reports: 'لا يوجد عمال مسجلون',
    days_present: 'يوم حضور', days_absent: 'يوم غياب', days_late: 'يوم تأخر', days_leave: 'يوم إجازة',
    // Archive
    archive_page_title: 'أرشيف العمال', archived_count: 'العمال المؤرشفون',
    archived_badge: 'مؤرشف', archive_date_lbl: 'تاريخ الأرشفة:',
    show_records: 'السجلات ▼', hide_records: 'إخفاء ▲',
    restore_title: 'استرجاع العامل', restore_msg: 'سيتم استرجاعه إلى قائمة العمال النشطين.',
    delete_perm_title: 'حذف نهائي', delete_perm_msg: 'سيتم حذف جميع سجلات حضوره نهائياً. لا يمكن التراجع.',
    empty_archive: 'الأرشيف فارغ', no_attendance_records: 'لا توجد سجلات حضور لهذا العامل',
    show_more: 'عرض المزيد', records_total: 'إجمالي السجلات:',
    // Login
    login_title: 'نظام الحضور والغياب', login_sub: 'تسجيل دخول المدير', pass_lbl: 'كلمة المرور',
    login_btn: 'دخول', checking: 'جاري التحقق...', wrong_pass: 'كلمة المرور غير صحيحة',
    default_pass_hint: 'كلمة المرور الافتراضية:',
    // Months
    months: ['جانفي','فيفري','مارس','أفريل','ماي','جوان','جويلية','أوت','سبتمبر','أكتوبر','نوفمبر','ديسمبر'],
    days: ['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'],
    weekly_off: 'إجازة أسبوعية',
    // Excel
    excel_worker_info: 'معلومات العامل', excel_daily: 'التفاصيل اليومية', excel_summary: 'ملخص',
    excel_day: 'اليوم', excel_date: 'التاريخ', excel_status: 'الحالة',
    excel_checkin: 'وقت الدخول', excel_checkout: 'وقت الخروج', excel_note: 'ملاحظة',
    excel_name: 'الاسم', excel_position: 'المنصب', excel_dept: 'القسم',
    excel_present: 'حاضر', excel_absent: 'غائب', excel_late: 'متأخر', excel_leave: 'إجازة',
    excel_rate: 'نسبة الحضور', excel_total: 'المجموع',
    total: 'الإجمالي',
    nav_settings: 'الإعدادات', settings_title: 'إعدادات النظام',
    settings_sub: 'تخصيص أيام العطلة الأسبوعية', weekly_off_label: 'أيام العطلة الأسبوعية',
    save_settings: 'حفظ الإعدادات', settings_saved: 'تم الحفظ بنجاح',
    settings_note: 'الأيام المحددة لن تُحسب ضمن أيام العمل في التقارير.',
    annual_leave: 'إجازة سنوية', days_annual_leave: 'يوم إجازة سنوية',
    annual_reports_title: 'التقارير السنوية', annual_reports_sub: 'ملخص حضور العمال على مدار السنة الكاملة',
    annual_export_excel: '📊 Excel سنوي', annual_print_pdf: '📄 PDF سنوي',
    annual_print_all: '📄 طباعة السنوي للكل', annual_export_all_excel: '📊 Excel سنوي للكل',
    col_month: 'الشهر', col_working_days: 'أيام العمل', annual_total: 'المجموع السنوي',
    back_to_monthly: '← التقارير الشهرية', view_annual: 'التقارير السنوية ←',
  },
  fr: {
    nav_dashboard: 'Tableau de bord', nav_workers: 'Employés', nav_attendance: 'Pointage',
    nav_reports: 'Rapports', nav_archive: 'Archive', nav_changePass: 'Changer le mot de passe', nav_logout: 'Déconnexion',
    cancel: 'Annuler', save: 'Enregistrer', edit: 'Modifier', archive_btn: 'Archiver',
    restore: '♻️ Restaurer', delete_final: 'Supprimer définitivement', confirm: 'Confirmer',
    present: 'Présent', absent: 'Absent', late: 'En retard', leave: 'Congé',
    change_pass_title: 'Changer le mot de passe', current_pass: 'Mot de passe actuel',
    new_pass: 'Nouveau mot de passe', confirm_pass: 'Confirmer le mot de passe',
    pass_changed: 'Mot de passe changé avec succès',
    dash_title: 'Tableau de bord', total_workers: 'Total employés', present_today: 'Présents aujourd\'hui',
    absent_today: 'Absents aujourd\'hui', late_today: 'En retard', on_leave: 'En congé',
    not_recorded: 'Non enregistré', absent_list: 'Absents aujourd\'hui', no_absents: 'Aucun absent enregistré',
    quick_links: 'Liens rapides', link_attendance: 'Enregistrer présence', link_workers: 'Gérer les employés',
    link_reports: 'Voir les rapports', no_workers_msg: 'Aucun employé enregistré', add_workers_btn: 'Ajouter des employés',
    workers_title: 'Gestion des employés', worker_count: 'employé(s)', add_worker: '+ Ajouter un employé',
    edit_worker_title: 'Modifier l\'employé', add_worker_title: 'Ajouter un employé',
    full_name: 'Nom complet *', name_ph: 'Entrez le nom complet',
    position_lbl: 'Poste / Fonction *', position_ph: 'Ex: maçon, électricien...',
    dept_lbl: 'Département', dept_ph: 'Ex: Production, Maintenance...', phone_lbl: 'Téléphone',
    start_date: 'Date d\'embauche', save_changes: 'Enregistrer', add_worker_btn: 'Ajouter',
    change_photo: 'Changer la photo', add_photo: '+ Ajouter une photo', delete_photo: 'Supprimer la photo',
    archive_title: 'Archiver l\'employé',
    archive_msg: 'L\'employé sera archivé avec tous ses enregistrements. Il n\'apparaîtra plus dans la liste quotidienne.',
    search_ph: 'Rechercher par nom, poste ou département...', col_photo: 'Photo', col_name: 'Nom',
    col_position: 'Poste', col_dept: 'Département', col_phone: 'Téléphone', col_start: 'Date d\'embauche',
    col_actions: 'Actions', no_workers: 'Aucun employé enregistré. Ajoutez le premier.', no_results: 'Aucun résultat.',
    pointage_title: 'Pointage', pointage_sub: 'Enregistrez la présence des employés chaque jour',
    date_lbl: 'Date :', mark_all: 'Tout marquer comme :', col_status: 'Statut',
    col_checkin: 'Heure d\'entrée', col_checkout: 'Heure de sortie', col_note: 'Note',
    add_note: '+ Note', note_title: 'Ajouter une note', note_ph: 'Écrivez une note ici...',
    no_workers_pointage: 'Aucun employé enregistré', go_add_workers: 'Allez ajouter des employés d\'abord',
    reports_title: 'Rapports mensuels', reports_sub: 'Résumé de présence par employé',
    year_lbl: 'Année :', month_lbl: 'Mois :', worker_lbl: 'Employé :', all_workers: 'Tous',
    download_pdf: '📄 Télécharger PDF', export_excel: '📊 Exporter Excel', print_all: '📄 Imprimer tout',
    export_all_excel: '📊 Exporter Excel tout', attendance_rate: 'Taux de présence', col_report: 'Rapport',
    month_summary: 'Résumé du mois', no_workers_reports: 'Aucun employé enregistré',
    days_present: 'j. présent', days_absent: 'j. absent', days_late: 'j. retard', days_leave: 'j. congé',
    archive_page_title: 'Archive des employés', archived_count: 'Employés archivés',
    archived_badge: 'Archivé', archive_date_lbl: 'Date d\'archivage :',
    show_records: 'Historique ▼', hide_records: 'Masquer ▲',
    restore_title: 'Restaurer l\'employé', restore_msg: 'Il sera restauré dans la liste des employés actifs.',
    delete_perm_title: 'Suppression définitive', delete_perm_msg: 'Tous les enregistrements seront supprimés définitivement.',
    empty_archive: 'Archive vide', no_attendance_records: 'Aucun enregistrement pour cet employé',
    show_more: 'Voir plus', records_total: 'Total des enregistrements :',
    login_title: 'Système de Pointage', login_sub: 'Connexion Administrateur', pass_lbl: 'Mot de passe',
    login_btn: 'Connexion', checking: 'Vérification...', wrong_pass: 'Mot de passe incorrect',
    default_pass_hint: 'Mot de passe par défaut :',
    months: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
    days: ['Dim','Lun','Mar','Mer','Jeu','Ven','Sam'],
    weekly_off: 'Repos hebdomadaire',
    excel_worker_info: 'Informations employé', excel_daily: 'Détails journaliers', excel_summary: 'Résumé',
    excel_day: 'Jour', excel_date: 'Date', excel_status: 'Statut',
    excel_checkin: 'Heure entrée', excel_checkout: 'Heure sortie', excel_note: 'Note',
    excel_name: 'Nom', excel_position: 'Poste', excel_dept: 'Département',
    excel_present: 'Présent', excel_absent: 'Absent', excel_late: 'Retard', excel_leave: 'Congé',
    excel_rate: 'Taux présence', excel_total: 'Total',
    total: 'Total',
    nav_settings: 'Paramètres', settings_title: 'Paramètres du système',
    settings_sub: 'Personnaliser les jours de repos hebdomadaire', weekly_off_label: 'Jours de repos',
    save_settings: 'Enregistrer', settings_saved: 'Enregistré avec succès',
    settings_note: 'Les jours sélectionnés ne seront pas comptés comme jours travaillés dans les rapports.',
    annual_leave: 'Congé annuel', days_annual_leave: 'j. congé annuel',
    annual_reports_title: 'Rapports annuels', annual_reports_sub: 'Résumé annuel de présence par employé',
    annual_export_excel: '📊 Excel annuel', annual_print_pdf: '📄 PDF annuel',
    annual_print_all: '📄 Imprimer annuel tout', annual_export_all_excel: '📊 Excel annuel tout',
    col_month: 'Mois', col_working_days: 'Jours travaillés', annual_total: 'Total annuel',
    back_to_monthly: '← Rapports mensuels', view_annual: 'Rapports annuels →',
  },
  en: {
    nav_dashboard: 'Dashboard', nav_workers: 'Workers', nav_attendance: 'Attendance',
    nav_reports: 'Reports', nav_archive: 'Archive', nav_changePass: 'Change Password', nav_logout: 'Logout',
    cancel: 'Cancel', save: 'Save', edit: 'Edit', archive_btn: 'Archive',
    restore: '♻️ Restore', delete_final: 'Delete Permanently', confirm: 'Confirm',
    present: 'Present', absent: 'Absent', late: 'Late', leave: 'Leave',
    change_pass_title: 'Change Password', current_pass: 'Current Password',
    new_pass: 'New Password', confirm_pass: 'Confirm Password',
    pass_changed: 'Password changed successfully',
    dash_title: 'Dashboard', total_workers: 'Total Workers', present_today: 'Present Today',
    absent_today: 'Absent Today', late_today: 'Late', on_leave: 'On Leave',
    not_recorded: 'Not Recorded', absent_list: 'Absent Today', no_absents: 'No absences recorded',
    quick_links: 'Quick Links', link_attendance: 'Record Today\'s Attendance', link_workers: 'Manage Workers',
    link_reports: 'View Reports', no_workers_msg: 'No workers registered yet', add_workers_btn: 'Add Workers',
    workers_title: 'Worker Management', worker_count: 'worker(s)', add_worker: '+ Add Worker',
    edit_worker_title: 'Edit Worker', add_worker_title: 'Add New Worker',
    full_name: 'Full Name *', name_ph: 'Enter full name',
    position_lbl: 'Position / Job *', position_ph: 'e.g. Mason, Electrician...',
    dept_lbl: 'Department', dept_ph: 'e.g. Production, Maintenance...', phone_lbl: 'Phone',
    start_date: 'Start Date', save_changes: 'Save Changes', add_worker_btn: 'Add Worker',
    change_photo: 'Change Photo', add_photo: '+ Add Photo', delete_photo: 'Delete Photo',
    archive_title: 'Archive Worker',
    archive_msg: 'The worker will be archived with all attendance records. They won\'t appear in daily attendance.',
    search_ph: 'Search by name, position or department...', col_photo: 'Photo', col_name: 'Name',
    col_position: 'Position', col_dept: 'Department', col_phone: 'Phone', col_start: 'Start Date',
    col_actions: 'Actions', no_workers: 'No workers registered. Add the first one.', no_results: 'No results found.',
    pointage_title: 'Attendance', pointage_sub: 'Record daily attendance for workers',
    date_lbl: 'Date:', mark_all: 'Mark all as:', col_status: 'Status',
    col_checkin: 'Check-in', col_checkout: 'Check-out', col_note: 'Note',
    add_note: '+ Note', note_title: 'Add Note', note_ph: 'Write a note here...',
    no_workers_pointage: 'No workers registered', go_add_workers: 'Go add workers first',
    reports_title: 'Monthly Reports', reports_sub: 'Attendance summary per worker',
    year_lbl: 'Year:', month_lbl: 'Month:', worker_lbl: 'Worker:', all_workers: 'All',
    download_pdf: '📄 Download PDF', export_excel: '📊 Export Excel', print_all: '📄 Print All',
    export_all_excel: '📊 Export All Excel', attendance_rate: 'Attendance Rate', col_report: 'Report',
    month_summary: 'Month Summary', no_workers_reports: 'No workers registered',
    days_present: 'present', days_absent: 'absent', days_late: 'late', days_leave: 'leave',
    archive_page_title: 'Workers Archive', archived_count: 'Archived workers',
    archived_badge: 'Archived', archive_date_lbl: 'Archived on:',
    show_records: 'Records ▼', hide_records: 'Hide ▲',
    restore_title: 'Restore Worker', restore_msg: 'They will be restored to the active workers list.',
    delete_perm_title: 'Permanent Deletion', delete_perm_msg: 'All attendance records will be permanently deleted.',
    empty_archive: 'Archive is empty', no_attendance_records: 'No attendance records for this worker',
    show_more: 'Show more', records_total: 'Total records:',
    login_title: 'Attendance System', login_sub: 'Manager Login', pass_lbl: 'Password',
    login_btn: 'Login', checking: 'Verifying...', wrong_pass: 'Incorrect password',
    default_pass_hint: 'Default password:',
    months: ['January','February','March','April','May','June','July','August','September','October','November','December'],
    days: ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
    weekly_off: 'Weekly off',
    excel_worker_info: 'Worker Information', excel_daily: 'Daily Details', excel_summary: 'Summary',
    excel_day: 'Day', excel_date: 'Date', excel_status: 'Status',
    excel_checkin: 'Check-in', excel_checkout: 'Check-out', excel_note: 'Note',
    excel_name: 'Name', excel_position: 'Position', excel_dept: 'Department',
    excel_present: 'Present', excel_absent: 'Absent', excel_late: 'Late', excel_leave: 'Leave',
    excel_rate: 'Attendance Rate', excel_total: 'Total',
    total: 'Total',
    nav_settings: 'Settings', settings_title: 'System Settings',
    settings_sub: 'Customize weekly off days', weekly_off_label: 'Weekly Off Days',
    save_settings: 'Save Settings', settings_saved: 'Saved successfully',
    settings_note: 'Selected days will not be counted as working days in reports.',
    annual_leave: 'Annual Leave', days_annual_leave: 'annual leave',
    annual_reports_title: 'Annual Reports', annual_reports_sub: 'Full-year attendance summary per worker',
    annual_export_excel: '📊 Annual Excel', annual_print_pdf: '📄 Annual PDF',
    annual_print_all: '📄 Print all annual', annual_export_all_excel: '📊 Annual Excel all',
    col_month: 'Month', col_working_days: 'Working Days', annual_total: 'Annual Total',
    back_to_monthly: '← Monthly Reports', view_annual: 'Annual Reports →',
  },
} as const;

export type TKey = keyof typeof T.ar;
export type Translations = typeof T.ar;

export function getT(lang: Lang): Translations {
  return T[lang] as Translations;
}
